# require_relative '../node_modules/react-native/scripts/react_native_pods'
# require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
  # Block from Expo
require File.join(`node --print "require.resolve('react-native/package.json')"`, "../scripts/react_native_pods")
require File.join(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`, "../native_modules")
require File.join(`node --print "require.resolve('react-native-unimodules/package.json')"`, "../cocoapods")
  # End Block from Expo
# Override Firebase SDK Version
$FirebaseSDKVersion = '8.5.0'

platform :ios, '11.0'

  # Line from Sentry
# use_frameworks! # This is important

target 'weplanapp' do
  # Line from Expo
  use_unimodules!
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
    )

  # Line from Sentry
  # pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '7.2.8'
  pod 'RNSentry', :path => '../node_modules/@sentry/react-native'

  target 'weplanappTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  # or pod 'Firebase/AnalyticsWithoutAdIdSupport'
  # for Analytics without IDFA collection capability

  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'GoogleSignIn'

  post_install do |installer|
    react_native_post_install(installer)
  end
end
